<?php

namespace NextDeveloper\Commons\Services;

use NextDeveloper\Commons\Services\AbstractServices\AbstractSocialMediaService;

/**
 * This class is responsible from managing the data for SocialMedia
 *
 * Class SocialMediaService.
 *
 * @package NextDeveloper\Commons\Database\Models
 */
class SocialMediaService extends AbstractSocialMediaService
{

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE

    public static function create(array $data)
    {
        //  Burada ID ve
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
