<?php

namespace NextDeveloper\Commons\Services;

use NextDeveloper\Commons\Services\AbstractServices\AbstractTagsService;
use NextDeveloper\IAM\Helpers\UserHelper;

/**
* This class is responsible from managing the data for Tags
*
* Class TagsService.
*
* @package NextDeveloper\Commons\Database\Models
*/
class TagsService extends AbstractTagsService {

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE

    public static function create(array $data)
    {
        if(array_key_exists('iam_account_id', $data)) {
            $data['iam_account_id'] = UserHelper::currentAccount()->id;
        } else {
            if(UserHelper::me() != null) {
                $data['iam_account_id'] = UserHelper::currentAccount()->id;
            }
        }

        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
